services:
  db:
    extends:
      file: services.yml
      service: db
    volumes:
       - db-data:/var/lib/postgresql/data
  api-admin:
    extends:
      file: services.yml
      service: api-admin

volumes:
  db-data:
